### ISSUE TITLE
Error when URock attempts to rotate geometries

### ISSUE THREAD

**Issue by bweeding** [UMEP-dev/UMEP-processing#59]
When attempting to run URock at any wind angle other than 0, I'm receiving the error detailed in the text file attached. 

I have attached the files and settings I'm using. This is with the most recent update to URock.

[URock_files.zip](https://github.com/UMEP-dev/UMEP-processing/files/13807393/URock_files.zip)
[urock_error_message.txt](https://github.com/UMEP-dev/UMEP-processing/files/13807406/urock_error_message.txt)

Cheers
Ben

**Comment by j3r3m1** [comment]
Hi Ben,
There is indeed a strange behavior of the URock algo for this specific case. However, the geometries you are using are polygonized but still look like raster, which wil
- affect the zones that will be created by URock (for example creating upstream or downstream zones where there should not be) which thus may give unexpected results
- take much more time that it is supposed to take

I suggest you to simplify the geometries by using the simplify function of the QGIS processing toolbox. Using the default Peucker algo with a tolerance of 1.5 m (slightly higher than the resolution of your initial raster I suppose), it works like a charm. We already simplify the geometries in the URock algo but the tolerance is lower than your 1 m, thus leading to almost no change. We cannot do that automatically since it might affect the results in a bad way if a user has a very small domain with small buildings.

Here is the buildings simplified: [build_simplified.zip](https://github.com/UMEP-dev/UMEP-processing/files/13812252/build_simplified.zip)

**Comment by bweeding** [comment]
Success!

I used the GRASS generalise Peucker at 1.5m on buildings and vegetation and it works.

Cheers
Ben
