### ISSUE TITLE
Higher wind speed at vegetation pixels

### ISSUE THREAD

**Issue by biglimp** [UMEP-dev/UMEP-processing#95]
@j3r3m1 , why do you think this is? Look at the example below. There seem to be higher wind speed (very minor) related to vegetation. Is there something to do with the fact that we are looking at 1.5 magl and we are looking at wind speed underneath the tree canopies?

![Image](https://github.com/user-attachments/assets/f6b89df8-c1ca-42ec-b4ab-cee15ffb76df)

![Image](https://github.com/user-attachments/assets/03c17d80-cb08-4bab-9df7-176934edc171)

**Comment by j3r3m1** [comment]
Nice map ! Yes this is probably due to the fact that it is under the tree canopy. Can you try putting all the vegetation up to the ground (setting to 0 all values of a column in the vegetation data being the bottom part of your vegetation - then you can call "vegetation crown base height").

I suppose this should remove the slight acceleration under the tree crown. If so this is fine URock works as it should.

**Comment by biglimp** [comment]
Yes, we should try that. Another question: What are the default attenuation factor for vegetation? I am think of increasing this abit...

**Comment by j3r3m1** [comment]
Here are the default values for the vegetation: https://github.com/UMEP-dev/UMEP-processing/blob/41dcd4782181c425378740d63a12c0d1fef884d6/functions/URock/GlobalVariables.py#L200

You can try to double the value (or more). Here are values coming from Cionco (1978) - brand new values I confess...:
![Image](https://github.com/user-attachments/assets/50fd87e2-917f-4729-8bd8-524e596a52ce)

Note that ideally a better vegetation scheme would be more appropriate than modifying the attenuation factor.

**Comment by j3r3m1** [comment]
What was the results of your tests ?

1. setting 0 the tree crown bottom height to 0
2. modifying the attenuation factor ?

**Comment by biglimp** [comment]
Setting it to 0 look better. We did not change attuation factor so I dont know.
